import Head from "next/head";
import About from "../components/About/About";
import Games from "../components/Games/Games";
import Hero from "../components/Hero/Hero";
import Navbar from "../components/Navbar/Navbar";
import NewSwiper from "../components/NewSwiper/NewSwiper";
import "swiper/css";
import People from "../components/People/People";
import Footer from "../components/Footer/Footer";
import Copyright from "../components/Copyright/Copyright";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <Hero />
      <About />
      <NewSwiper />
      <Games />
      <People />
      <Footer />
      <Copyright />
    </div>
  );
}
